### ISSUE TITLE
Production mode

### ISSUE THREAD

**Issue by Flavien-Pensato** [cubyn/payline#4]
Hi,

The production mode doesn't seem implement yet.

Best

**Comment by louisremi** [comment]
How did you manage to use production mode? It seems I can only use that lib in homologation mode!

**Comment by louisremi** [comment]
Alright, I figured out I needed an additional argument to the `Payline` constructor (see Readme) and to provide my own wsdl (I just copied the wsdl provided in the src dir and modified the endpoint urls at the very end of the file to replace `homologation` with `services`).
